version: '2.1'
services:
  stub:
    build: ./docker/stubby
    container_name: stub
    volumes:
      - "./docker/stubby:/stubby"
    entrypoint:
      - stubby
      - -d
      - stub.json
    ports:
      - 8882:8882
      - 8889:8889
  bff:
    build: .
    container_name: bff-middleware
    ports: 
      - 9000:9000